### ISSUE TITLE
Error while running bundle exec jekyll serve

### ISSUE THREAD

**Issue by ajbozdar** [merlos/jekyll-auto-image#7]
I am afraid, if the plug-in has compatibility issue with Jekyll 3.3. It produces following error when I run bundle exec Jekyll serve to run Jekyll.
`jekyll 3.3.0 | Error:  undefined method `transform' for #<Jekyll::Renderer:0x00000002be0c38>`

Let me know, if I could be of further help.

**Comment by sivy** [comment]
I get this as well with Jekyll 3.3.0 on Gitlab Pages

**Comment by sivy** [comment]
Looks like the issue is in:

https://github.com/merlos/jekyll-auto-image/blob/82a74b1991ff379b3c42d401b27221fb8764cfc1/lib/jekyll-auto-image.rb#L84-L88

``` ruby
      if page.class == Jekyll::Document # for jekyll 3.0 posts & collections
        htmled = Jekyll::Renderer.new(@site, page, @site.site_payload).convert(page.content)
      else 
        htmled = page.transform # for jekyll 2.x pages
      end
```

Wondering if `page.class == Jekyll::Document` is still true for 3.3?

**Comment by sivy** [comment]
I'm not a strong ruby programmer, but in Jekyll::Page (https://github.com/jekyll/jekyll/blob/5e93ca63538c2bb98d35c9e3f3996b6e8fe079b7/lib/jekyll/page.rb#L3) I see this:

``` ruby
module Jekyll
  class Page
    include Convertible
```

So maybe rather than checking `page.class == Jekyll::Document`, it would be better to do:

``` ruby
if page < Jekyll::Convertible # for jekyll 3.? posts & collections
  htmled = Jekyll::Renderer.new(@site, page, @site.site_payload).convert(page.content)
else 
  htmled = page.transform # for jekyll 2.x pages
end
```

**Comment by merlos** [comment]
Hi! 
Yep, it seems that jekyll 3.3 broke the plugin :_( 

I made the change proposed by @sivy, but running the test I'm having problems. First, I had to change the calls to .clone for calls to .dup. But I still I'm getting errors... 

```
Jekyll::AutoImageTest#test_: AutoImage should find image with weird characters in name. :
RuntimeError: can't modify frozen Hash
    /Users/merlos/.rvm/gems/ruby-2.2.2/gems/jekyll-3.3.0/lib/jekyll/converters/markdown/kramdown_parser.rb:33:in `setup'
    /Users/merlos/.rvm/gems/ruby-2.2.2/gems/jekyll-3.3.0/lib/jekyll/converters/markdown/kramdown_parser.rb:22:in `initialize'
    /Users/merlos/.rvm/gems/ruby-2.2.2/gems/jekyll-3.3.0/lib/jekyll/converters/markdown.rb:32:in `new'
    /Users/merlos/.rvm/gems/ruby-2.2.2/gems/jekyll-3.3.0/lib/jekyll/converters/markdown.rb:32:in `get_processor'
    /Users/merlos/.rvm/gems/ruby-2.2.2/gems/jekyll-3.3.0/lib/jekyll/converters/markdown.rb:10:in `setup'
    /Users/merlos/.rvm/gems/ruby-2.2.2/gems/jekyll-3.3.0/lib/jekyll/converters/markdown.rb:74:in `convert'
    /Users/merlos/.rvm/gems/ruby-2.2.2/gems/jekyll-3.3.0/lib/jekyll/renderer.rb:109:in `block in convert'
    /Users/merlos/.rvm/gems/ruby-2.2.2/gems/jekyll-3.3.0/lib/jekyll/renderer.rb:107:in `each'
    /Users/merlos/.rvm/gems/ruby-2.2.2/gems/jekyll-3.3.0/lib/jekyll/renderer.rb:107:in `reduce'
    /Users/merlos/.rvm/gems/ruby-2.2.2/gems/jekyll-3.3.0/lib/jekyll/renderer.rb:107:in `convert'
    /Users/merlos/Projects/merlos.org/jekyll-auto-image/lib/jekyll-auto-image.rb:86:in `get_image'
    /Users/merlos/Projects/merlos.org/jekyll-auto-image/test/test_jekyll_auto_image.rb:115:in `block (2 levels) in <class:AutoImageTest>'
    /Users/merlos/.rvm/gems/ruby-2.2.2/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:413:in `instance_exec'
    /Users/merlos/.rvm/gems/ruby-2.2.2/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:413:in `block in create_test_from_should_hash'
```

I've opened the branch https://github.com/merlos/jekyll-auto-image/tree/bugfix/jekyll-3-3-0
If anyone has some idea on how to solve these problems... help is welcome :)

Thanks, Juan.
